spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    schema: classpath:schema.sql

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    ROOT: INFO