DROP TABLE IF EXISTS TICKER_INFO;
CREATE TABLE TICKER_INFO(
  ID IDENTITY PRIMARY KEY,
  TICKER VARCHAR(255) NOT NULL,
  PERIOD INTEGER NOT NULL,
  DATE_TIME SMALLDATETIME NOT NULL,
  PRICE NUMERIC NOT NULL
);
