server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost
      database: books-db
      port: 0

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    schema: classpath:schema.sql

  jpa:
    generate-ddl: false
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2-console

  shell:
    interactive:
      enabled: true

  batch:
    job:
      enabled: false